/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gcloud.pubsub;
@org.apache.avro.specific.AvroGenerated
public enum StatusType implements org.apache.avro.generic.GenericEnumSymbol<StatusType> {
  STARTED, FINISHED, ABORTED, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"StatusType\",\"namespace\":\"gcloud.pubsub\",\"symbols\":[\"STARTED\",\"FINISHED\",\"ABORTED\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
